version: '2'

volumes:
 orderer1.ord.fedchain:
 orderer2.ord.fedchain:
 orderer3.ord.fedchain:
 peer1.org1.fedchain:
 peer2.org1.fedchain:
 peer3.org1.fedchain:

networks:
  byfn:

services:

  orderer1.ord.fedchain:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer1.ord.fedchain
    environment:
      - ORDERER_GENERAL_LISTENPORT=7050
    networks:
    - byfn
    volumes:
        - ./artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/ord.fedchain/orderers/orderer1.ord.fedchain/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/ord.fedchain/orderers/orderer1.ord.fedchain/tls:/var/hyperledger/orderer/tls
        - orderer1.ord.fedchain:/var/hyperledger/production/orderer
    ports:
    - 7050:7050
  orderer2.ord.fedchain:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer2.ord.fedchain
    environment:
      - ORDERER_GENERAL_LISTENPORT=8050
    networks:
    - byfn
    volumes:
        - ./artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/ord.fedchain/orderers/orderer2.ord.fedchain/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/ord.fedchain/orderers/orderer2.ord.fedchain/tls:/var/hyperledger/orderer/tls
        - orderer2.ord.fedchain:/var/hyperledger/production/orderer
    ports:
    - 8050:8050  

  orderer3.ord.fedchain:
    extends:
      file: base.yaml
      service: orderer-base
    container_name: orderer3.ord.fedchain
    environment:
      - ORDERER_GENERAL_LISTENPORT=9050
    networks:
    - byfn
    volumes:
        - ./artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/ord.fedchain/orderers/orderer3.ord.fedchain/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/ord.fedchain/orderers/orderer3.ord.fedchain/tls:/var/hyperledger/orderer/tls
        - orderer3.ord.fedchain:/var/hyperledger/production/orderer
    ports:
    - 9050:9050  

  peer1.org1.fedchain:
    container_name: peer1.org1.fedchain
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.fedchain
      - CORE_PEER_ADDRESS=peer1.org1.fedchain:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.fedchain:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.fedchain:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.fedchain:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.fedchain/peers/peer1.org1.fedchain/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.fedchain/peers/peer1.org1.fedchain/tls:/etc/hyperledger/fabric/tls
        - ./chaincode/external_builder:/builders/external
        - ./fabric-config/core.yaml:/etc/hyperledger/fabric/core.yaml
        - peer1.org1.fedchain:/var/hyperledger/production
    ports:
      - 7051:7051
    networks:
      - byfn
  
  peer2.org1.fedchain:
    container_name: peer2.org1.fedchain
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.org1.fedchain
      - CORE_PEER_ADDRESS=peer2.org1.fedchain:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer2.org1.fedchain:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.fedchain:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.fedchain:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.fedchain/peers/peer2.org1.fedchain/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.fedchain/peers/peer2.org1.fedchain/tls:/etc/hyperledger/fabric/tls
        - ./chaincode/external_builder:/builders/external
        - ./fabric-config/core.yaml:/etc/hyperledger/fabric/core.yaml
        - peer2.org1.fedchain:/var/hyperledger/production
    ports:
      - 8051:8051
    networks:
      - byfn 
    
  peer3.org1.fedchain:
    container_name: peer3.org1.fedchain
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer3.org1.fedchain
      - CORE_PEER_ADDRESS=peer3.org1.fedchain:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer3.org1.fedchain:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.fedchain:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer3.org1.fedchain:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.fedchain/peers/peer3.org1.fedchain/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.fedchain/peers/peer3.org1.fedchain/tls:/etc/hyperledger/fabric/tls
        - ./chaincode/external_builder:/builders/external
        - ./fabric-config/core.yaml:/etc/hyperledger/fabric/core.yaml
        - peer3.org1.fedchain:/var/hyperledger/production
    ports:
      - 9051:9051
    networks:
      - byfn 

  ca.org1.fedchain:
      extends:
        file: base.yaml
        service: ca-base
      environment:
        - FABRIC_CA_SERVER_CA_NAME=ca-org1
        - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.fedchain-cert.pem
        - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
        - FABRIC_CA_SERVER_PORT=7054
      ports:
        - "7054:7054"
      command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.fedchain-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b rcaadmin:password -d'
      volumes:
        - ./crypto-config/peerOrganizations/org1.fedchain/ca/:/etc/hyperledger/fabric-ca-server-config
      container_name: ca.org1.fedchain
      networks:
      - byfn

  couchdb:
    container_name: couchdb
    image: couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=dbadmin
      - COUCHDB_PASSWORD=password
    ports:
      - 5984:5984
    networks:
      - byfn 
      
  cli:
      container_name: cli
      image: hyperledger/fabric-tools:$IMAGE_TAG
      tty: true
      stdin_open: true
      environment:
        - GOPATH=/opt/gopath
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        #- FABRIC_LOGGING_SPEC=DEBUG
        - FABRIC_LOGGING_SPEC=INFO
        - CORE_PEER_ID=cli
        - CORE_PEER_ADDRESS=peer1.org1.fedchain:7051
        - CORE_PEER_LOCALMSPID=Org1MSP
        - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.fedchain/users/Admin@org1.fedchain/msp
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.fedchain/peers/peer1.org1.fedchain/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.fedchain/peers/peer1.org1.fedchain/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.fedchain/peers/peer1.org1.fedchain/tls/ca.crt
        - CORE_CHAINCODE_EXTERNALBUILDERSPATH=/builders/external
        - CORE_CHAINCODE_EXTERNALBUILDERS_NAME=external-builder
        - GODEBUG=netdns=go
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: /bin/bash
      volumes:
          - /var/run/:/host/var/run/
          - ./chaincode/:/opt/gopath/src/github.com/chaincode
          - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          - ./artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
          - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
      depends_on:
      - peer1.org1.fedchain
      - peer2.org1.fedchain
      - peer3.org1.fedchain

      networks:
        - byfn      


